import { Box, Flex, Heading, Text } from "@chakra-ui/react";
import React, { useEffect } from "react";
import DataTable from "react-data-table-component";
import { CustomButton, CustomButtonText } from "../Button/Button";
import { useNavigate } from "react-router-dom";

export const DataTAble = () => {
  const columns = [
    { name: "Date", selector: (row) => row.date ,sortable:true},
    { name: "GK PNR", selector: (row) => row.gk_pnr },
    { name: "HK PNR", selector: (row) => row.hk_pnr },
    { name: "Fare Exp. Date", selector: (row) => row.fare_exp_date },
    { name: "Airline PNR", selector: (row) => row.airline_pnr },
    { name: "BMS ID", selector: (row) => row.bms_id },
    { name: "Source", selector: (row) => row.source },
    { name: "Creation PSEUDO", selector: (row) => row.creation_pseudo },
    { name: "Airline", selector: (row) => row.airline },
    { name: "No. of Pax", selector: (row) => row.pax },
    { name: "Domestic International", selector: (row) => row.domestic },
    { name: "Departure", selector: (row) => row.departure },
    { name: "Destination", selector: (row) => row.destination },
    { name: "Dept. Date", selector: (row) => row.departure_Date },
    { name: "FXL / FXR", selector: (row) => row.fxl_fxr },
    { name: "Online Fare", selector: (row) => row.fare },
    { name: "Topline", selector: (row) => row.topline },
    { name: "GPM/MCO", selector: (row) => row.gpm_mco },
    { name: "Breaking Fee", selector: (row) => row.breaking_Fee },
    { name: "Surcharge", selector: (row) => row.surcharge },
    { name: "Net MCO", selector: (row) => row.net_mco },
    { name: "Agent", selector: (row) => row.agent },
    { name: "Remarks", selector: (row) => row.remarks },
    { name: "TKT Status", selector: (row) => row.tkt_status },
    { name: "MCO Status", selector: (row) => row.mco_status },
    { name: "Charge", selector: (row) => row.charge },
    { name: "Issued By", selector: (row) => row.issued },
    { name: "CCV Status", selector: (row) => row.ccv_status },
    { name: "I Agree", selector: (row) => row.i_agree },
    { name: "Docs", selector: (row) => row.docs },
    { name: "MCO Charged Date", selector: (row) => row.mco_chargedDate },
    { name: "PS Agent", selector: (row) => row.psAgent },
  ];

  const data = [
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "3-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
    {
      date: "1-Sep",
      gk_pnr: "2UDEMR",
      hk_pnr: "PHL-2VIB4Z",
      fare_exp_date: "3-Sep",
      airline_pnr: "GYWL3W",
      bms_id: "43534",
      source: "Meta Call",
      creation_pseudo: "DSFAds",
      airline: "DL",
      pax: "3",
      domestic: "SDF",
      departure: "3-Sept",
      destination: "una",
      departure_Date: "4-Sept",
      fxl_fxr: "FDS",
      fare: "343",
      topline: "sdf",
      gpm_mco: "SDF",
      breaking_Fee: "343",
      surcharge: "43",
      net_mco: "dsf",
      agent: "Kumar",
      remarks: "SDFSDF SF F AF",
      tkt_status: "true",
      mco_status: "true",
      charge: "434",
      issued: "5-Sept",
      ccv_status: "completed",
      i_agree: "Yes",
      docs: "PPF",
      mco_chargedDate: "5-Sept.",
      psAgent: "Ankit",
    },
  
  ];
  const customStyles = {
    rows: {
        style: {
            minHeight: '62px',
            fontSize:"13px"
        },
    },
    headCells: {
        style: {
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize:"14px"
        },
    },
    cells: {
        style: {
            paddingLeft: '8px',
            paddingRight: '8px'
        },
    },
};
const navigate=useNavigate()
let token = JSON.parse(localStorage.getItem('token')) || '';
useEffect(()=>{
if(!token){
 return navigate("/");
}
},[token])

  return (
    <>
      <Box p={6} py={3}>
    <Flex justifyContent={'space-between'}>
      <Heading  lineHeight={1.1}
            fontWeight={600}
            fontSize={{ base: '3xl', sm: '4xl' }} color={"blue.500"}>
          Booked Data
        </Heading>
      <CustomButton link={"/book"} text={"Book ticket"}/>
    </Flex>
     
      <DataTable customStyles={customStyles} columns={columns} data={data} fixedHeader pagination></DataTable> </Box>
</>
  );
};
